server:
  port: 10086
spring:
  application:
    name: ly_registry  #当前项目名
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:10086/eureka
    fetch-registry: true    # 是否拉取服务  因为当前项目本身就是注册中心了 不需要拉取
    register-with-eureka: true  #是否需要注册到注册中心  因为当前项目本身就是注册中心了 不需要注册
  server:
    enable-self-preservation: false