server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/saas-export
    username: root
    password: root
  application:
    name: leyou_service  #当前项目名
eureka:
   client:
     service-url:
      defaultZone: http://127.0.0.1:10086/eureka
     fetch-registry: true    # 需要从注册中心拉取服务
     register-with-eureka: true # 需要把自己注册到注